version: '3'
services:
  go-service:
    build:
      context: ./go-service
    ports:
      - "50051:50051"
    networks:
      - backend
  node-service:
    build:
      context: ./node-service
    ports:
      - "50052:50052"
    networks:
      - backend
  postgres-go:
    image: postgres
    environment:
      POSTGRES_DB: go_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend
  postgres-node:
    image: postgres
    environment:
      POSTGRES_DB: node_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - backend
networks:
  backend:
