// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,  
  username,
  full_name,
  hashed_password,
  is_email_verified
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING email, username, full_name, hashed_password, is_email_verified, password_changed_at, created_at
`

type CreateUserParams struct {
	Email           string `json:"email"`
	Username        string `json:"username"`
	FullName        string `json:"full_name"`
	HashedPassword  string `json:"hashed_password"`
	IsEmailVerified bool   `json:"is_email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.FullName,
		arg.HashedPassword,
		arg.IsEmailVerified,
	)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT email, username, full_name, hashed_password, is_email_verified, password_changed_at, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  hashed_password = COALESCE($1, hashed_password),
  full_name = COALESCE($2, full_name),
  email = COALESCE($3, email),
  is_email_verified = COALESCE($4, is_email_verified)
WHERE
  username = $5
RETURNING email, username, full_name, hashed_password, is_email_verified, password_changed_at, created_at
`

type UpdateUserParams struct {
	HashedPassword  pgtype.Text `json:"hashed_password"`
	FullName        pgtype.Text `json:"full_name"`
	Email           pgtype.Text `json:"email"`
	IsEmailVerified pgtype.Bool `json:"is_email_verified"`
	Username        string      `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
		arg.IsEmailVerified,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
